"""Deterministic processed-to-LaTeX generation for LOCUS."""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import statistics
from pathlib import Path
from typing import Any

from .deployment import PERFORMANCE_SCENARIOS
from .performance_processing import (
    BOOTSTRAP_ALGORITHM,
    PROCESSED_PERFORMANCE_VERSION,
    PROCESSED_PERFORMANCE_VERSION_V2,
    QUANTILE_METHOD,
    serialize_processed_performance,
    validate_processed_performance,
)
from .redaction import OutputSafetyError, validate_public_output

PAPER_INPUTS_VERSION = "LOCUS-performance-paper-inputs-v1"
PAPER_INPUTS_VERSION_V2 = "LOCUS-performance-paper-inputs-v2"
PAPER_FORMAT_VERSION = "LOCUS-performance-latex-rows-v1"
DECIMAL_PLACES = 3

LATENCY_ROWS = "latency_rows.tex"
PHASE_ROWS = "phase_rows.tex"
TRAFFIC_ROWS = "traffic_rows.tex"
STORAGE_ROWS = "storage_rows.tex"
MANIFEST = "manifest.json"

_ROW_FILES = (LATENCY_ROWS, PHASE_ROWS, TRAFFIC_ROWS, STORAGE_ROWS)
_ALL_FILES = (*_ROW_FILES, MANIFEST)
_DIGEST = re.compile(r"[0-9a-f]{64}\Z")
_COMMIT = re.compile(r"[0-9a-f]{40}\Z")
_IDENTIFIER = re.compile(r"[a-z0-9][a-z0-9._-]{0,63}\Z")
_SOURCE_PATH = re.compile(
    r"experiments/processed/(performance-v[12])/"
    r"[a-z0-9][a-z0-9._-]{0,63}\.json\Z"
)
_SCENARIO_LABELS = {
    "enroll-recover-success-v1": "Correct recovery",
    "recover-one-party-unavailable-v1": "Party 1 unavailable",
    "recover-wrong-input-v1": "Wrong input",
}
_PHASE_LABELS = (
    ("client_setup", "Client setup"),
    ("resolver", "Resolver"),
    ("cloud", "Cloud"),
    ("authorization", "Authorization"),
    ("commitment", "TPASS commitment"),
    ("response", "TPASS response"),
    ("status_check", "Status check"),
    ("finalization", "Finalization"),
    ("unclassified", "Unclassified"),
)
_ROLE_LABELS = (
    ("authorization", "Authorization"),
    ("cloud", "Cloud"),
    ("resolver", "Resolver"),
    ("tpass", "TPASS"),
)


class PerformancePaperError(Exception):
    """The processed source or generated manuscript inputs are invalid."""


def _source_corpus_version(source_path: object) -> str:
    if not isinstance(source_path, str):
        raise PerformancePaperError("invalid processed performance source")
    match = _SOURCE_PATH.fullmatch(source_path)
    if match is None:
        raise PerformancePaperError("invalid processed performance source")
    return match.group(1)


def _exact_dict(value: object, fields: set[str], label: str) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != fields:
        raise PerformancePaperError(f"invalid {label}")
    return value


def _repo_relative(repo_root: Path, path: Path, *, label: str) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except (OSError, ValueError) as exc:
        raise PerformancePaperError(f"{label} escaped repository") from exc


def _sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _format_number(value: object, *, decimals: int = DECIMAL_PLACES) -> str:
    if (
        not isinstance(value, (int, float))
        or isinstance(value, bool)
        or not math.isfinite(value)
        or value < 0
    ):
        raise PerformancePaperError("invalid generated numeric value")
    return f"{float(value):.{decimals}f}"


def _format_count(value: object) -> str:
    if (
        not isinstance(value, (int, float))
        or isinstance(value, bool)
        or not math.isfinite(value)
        or value < 0
    ):
        raise PerformancePaperError("invalid generated byte value")
    numeric = float(value)
    return str(int(numeric)) if numeric.is_integer() else f"{numeric:.1f}"


def _tex_header(*, description: str, source_sha256: str) -> list[str]:
    return [
        f"% {PAPER_FORMAT_VERSION}",
        f"% {description}",
        f"% source-sha256: {source_sha256}",
        "% Generated by tasks.py generate-performance-paper; do not edit.",
    ]


def _summary_range(summary: dict[str, Any], lower: str, upper: str) -> str:
    return f"{_format_number(summary[lower])}--{_format_number(summary[upper])}"


def _latency_rows(processed: dict[str, Any], source_sha256: str) -> bytes:
    lines = _tex_header(
        description=(
            "operation & n & median ms & p25--p75 ms & p05--p95 ms & median 95pct CI ms"
        ),
        source_sha256=source_sha256,
    )
    entries = [
        ("Enrollment", processed["enrollment_latency_ms"]),
        *[
            (
                _SCENARIO_LABELS[scenario_id],
                processed["scenarios"][scenario_id]["latency_ms"]["total"],
            )
            for scenario_id in PERFORMANCE_SCENARIOS
        ],
    ]
    for label, distribution in entries:
        summary = distribution["summary"]
        confidence = summary["median_ci95"]
        lines.append(
            " & ".join(
                (
                    label,
                    str(summary["count"]),
                    _format_number(summary["median"]),
                    _summary_range(summary, "p25", "p75"),
                    _summary_range(summary, "p05", "p95"),
                    (
                        f"{_format_number(confidence['lower'])}--"
                        f"{_format_number(confidence['upper'])}"
                    ),
                )
            )
            + r" \\"
        )
    return ("\n".join(lines) + "\n").encode("ascii")


def _phase_rows(processed: dict[str, Any], source_sha256: str) -> bytes:
    lines = _tex_header(
        description="scenario & phase & n & median ms & p25--p75 ms",
        source_sha256=source_sha256,
    )
    for scenario_id in PERFORMANCE_SCENARIOS:
        scenario = processed["scenarios"][scenario_id]
        for field, phase_label in _PHASE_LABELS:
            summary = scenario["latency_ms"][field]["summary"]
            lines.append(
                " & ".join(
                    (
                        _SCENARIO_LABELS[scenario_id],
                        phase_label,
                        str(summary["count"]),
                        _format_number(summary["median"]),
                        _summary_range(summary, "p25", "p75"),
                    )
                )
                + r" \\"
            )
    return ("\n".join(lines) + "\n").encode("ascii")


def _integer_range(distribution: dict[str, Any]) -> str:
    summary = distribution["summary"]
    return f"{summary['min']}--{summary['max']}"


def _integer_median(distribution: dict[str, Any]) -> str:
    return _format_count(statistics.median(distribution["series"]))


def _traffic_rows(processed: dict[str, Any], source_sha256: str) -> bytes:
    lines = _tex_header(
        description=(
            "scenario & role & sent median B & sent min--max B "
            "& received median B & received min--max B"
        ),
        source_sha256=source_sha256,
    )
    for scenario_id in PERFORMANCE_SCENARIOS:
        scenario = processed["scenarios"][scenario_id]
        for role, role_label in _ROLE_LABELS:
            sent = scenario["application_bytes"][role]["sent"]
            received = scenario["application_bytes"][role]["received"]
            lines.append(
                " & ".join(
                    (
                        _SCENARIO_LABELS[scenario_id],
                        role_label,
                        _integer_median(sent),
                        _integer_range(sent),
                        _integer_median(received),
                        _integer_range(received),
                    )
                )
                + r" \\"
            )
    return ("\n".join(lines) + "\n").encode("ascii")


def _storage_rows(processed: dict[str, Any], source_sha256: str) -> bytes:
    lines = _tex_header(
        description=(
            "scenario & role & before median B & before min--max B "
            "& after median B & after min--max B"
        ),
        source_sha256=source_sha256,
    )
    for scenario_id in PERFORMANCE_SCENARIOS:
        storage = processed["scenarios"][scenario_id]["storage"]
        entries = [
            (
                "Cloud object",
                storage["cloud_object_bytes"],
                storage["cloud_object_bytes"],
            ),
            (
                "Client bundle",
                storage["before"]["client_bytes"],
                storage["after"]["client_bytes"],
            ),
            *[
                (
                    f"Party {party}",
                    storage["before"]["party_bytes"][party - 1]["values"],
                    storage["after"]["party_bytes"][party - 1]["values"],
                )
                for party in range(1, 6)
            ],
        ]
        for role_label, before, after in entries:
            lines.append(
                " & ".join(
                    (
                        _SCENARIO_LABELS[scenario_id],
                        role_label,
                        _integer_median(before),
                        _integer_range(before),
                        _integer_median(after),
                        _integer_range(after),
                    )
                )
                + r" \\"
            )
    return ("\n".join(lines) + "\n").encode("ascii")


def build_performance_paper_inputs(
    *,
    processed: object,
    source_path: str,
    source_bytes: bytes,
) -> tuple[dict[str, Any], dict[str, bytes]]:
    """Build the exact row fragments and provenance manifest."""

    validated = validate_processed_performance(processed)
    canonical = serialize_processed_performance(validated)
    if source_bytes != canonical:
        raise PerformancePaperError("invalid processed performance source")
    corpus_version = _source_corpus_version(source_path)
    inputs = validated["source"]["inputs"]
    if inputs[0]["path"].split("/")[2] != corpus_version:
        raise PerformancePaperError(
            "processed source version does not match its raw corpus"
        )
    source_sha256 = _sha256(source_bytes)
    outputs = {
        LATENCY_ROWS: _latency_rows(validated, source_sha256),
        PHASE_ROWS: _phase_rows(validated, source_sha256),
        TRAFFIC_ROWS: _traffic_rows(validated, source_sha256),
        STORAGE_ROWS: _storage_rows(validated, source_sha256),
    }
    source = validated["source"]
    processing = validated["processing"]
    bootstrap = processing["bootstrap"]
    manifest = {
        "artifact": (
            PAPER_INPUTS_VERSION_V2
            if corpus_version == "performance-v2"
            else PAPER_INPUTS_VERSION
        ),
        "format": {
            "decimal_places": DECIMAL_PLACES,
            "version": PAPER_FORMAT_VERSION,
        },
        "outputs": [
            {
                "path": f"paper/generated/{corpus_version}/{name}",
                "sha256": _sha256(outputs[name]),
            }
            for name in _ROW_FILES
        ],
        "processing": {
            "bootstrap_algorithm": bootstrap["algorithm"],
            "bootstrap_resamples": bootstrap["resamples"],
            "bootstrap_seed": bootstrap["seed"],
            "quantile_method": processing["quantile_method"],
        },
        "source": {
            "artifact": validated["artifact"],
            "experiment_id": source["experiment_id"],
            "git_commit": source["git_commit"],
            "host_id": source["host"]["id"],
            "path": source_path,
            "sha256": source_sha256,
        },
    }
    return validate_performance_paper_manifest(manifest, outputs=outputs), outputs


def validate_performance_paper_manifest(
    value: object, *, outputs: dict[str, bytes] | None = None
) -> dict[str, Any]:
    """Validate the exact generated-input manifest and optional output bytes."""

    manifest = _exact_dict(
        value,
        {"artifact", "format", "outputs", "processing", "source"},
        "performance paper manifest",
    )
    if manifest["artifact"] not in {PAPER_INPUTS_VERSION, PAPER_INPUTS_VERSION_V2}:
        raise PerformancePaperError("unsupported performance paper manifest")
    paper_format = _exact_dict(
        manifest["format"], {"decimal_places", "version"}, "paper format"
    )
    if paper_format != {
        "decimal_places": DECIMAL_PLACES,
        "version": PAPER_FORMAT_VERSION,
    }:
        raise PerformancePaperError("invalid performance paper format")
    processing = _exact_dict(
        manifest["processing"],
        {
            "bootstrap_algorithm",
            "bootstrap_resamples",
            "bootstrap_seed",
            "quantile_method",
        },
        "paper processing provenance",
    )
    if (
        processing["bootstrap_algorithm"] != BOOTSTRAP_ALGORITHM
        or processing["quantile_method"] != QUANTILE_METHOD
        or not isinstance(processing["bootstrap_resamples"], int)
        or isinstance(processing["bootstrap_resamples"], bool)
        or not 1_000 <= processing["bootstrap_resamples"] <= 100_000
        or not isinstance(processing["bootstrap_seed"], int)
        or isinstance(processing["bootstrap_seed"], bool)
        or not 0 <= processing["bootstrap_seed"] <= 2**64 - 1
    ):
        raise PerformancePaperError("invalid paper processing provenance")
    source = _exact_dict(
        manifest["source"],
        {
            "artifact",
            "experiment_id",
            "git_commit",
            "host_id",
            "path",
            "sha256",
        },
        "paper source provenance",
    )
    try:
        corpus_version = _source_corpus_version(source["path"])
    except PerformancePaperError as exc:
        raise PerformancePaperError("invalid paper source provenance") from exc
    expected_processed_artifact = (
        PROCESSED_PERFORMANCE_VERSION_V2
        if corpus_version == "performance-v2"
        else PROCESSED_PERFORMANCE_VERSION
    )
    expected_manifest_artifact = (
        PAPER_INPUTS_VERSION_V2
        if corpus_version == "performance-v2"
        else PAPER_INPUTS_VERSION
    )
    if (
        manifest["artifact"] != expected_manifest_artifact
        or source["artifact"] != expected_processed_artifact
        or not isinstance(source["experiment_id"], str)
        or _IDENTIFIER.fullmatch(source["experiment_id"]) is None
        or not isinstance(source["git_commit"], str)
        or _COMMIT.fullmatch(source["git_commit"]) is None
        or not isinstance(source["host_id"], str)
        or _IDENTIFIER.fullmatch(source["host_id"]) is None
        or source["host_id"] == "unlabeled-local-host"
        or not isinstance(source["sha256"], str)
        or _DIGEST.fullmatch(source["sha256"]) is None
    ):
        raise PerformancePaperError("invalid paper source provenance")
    raw_outputs = manifest["outputs"]
    if not isinstance(raw_outputs, list) or len(raw_outputs) != len(_ROW_FILES):
        raise PerformancePaperError("invalid paper output manifest")
    for name, raw_output in zip(_ROW_FILES, raw_outputs, strict=True):
        output = _exact_dict(raw_output, {"path", "sha256"}, "paper output")
        if (
            output["path"] != f"paper/generated/{corpus_version}/{name}"
            or not isinstance(output["sha256"], str)
            or _DIGEST.fullmatch(output["sha256"]) is None
        ):
            raise PerformancePaperError("invalid paper output")
        if outputs is not None and (
            set(outputs) != set(_ROW_FILES)
            or output["sha256"] != _sha256(outputs[name])
        ):
            raise PerformancePaperError("paper output digest mismatch")
    try:
        validate_public_output(manifest)
    except OutputSafetyError as exc:
        raise PerformancePaperError("unsafe performance paper manifest") from exc
    return manifest


def serialize_performance_paper_manifest(value: object) -> bytes:
    """Return canonical ASCII JSON for one validated paper-input manifest."""

    manifest = validate_performance_paper_manifest(value)
    return (
        json.dumps(
            manifest,
            allow_nan=False,
            ensure_ascii=True,
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    ).encode("ascii")


def _read_existing(path: Path) -> bytes:
    try:
        if path.is_symlink() or not path.is_file():
            raise PerformancePaperError("invalid existing paper input")
        return path.read_bytes()
    except OSError as exc:
        raise PerformancePaperError("invalid existing paper input") from exc


def write_performance_paper_inputs(
    *,
    repo_root: Path,
    output_dir: Path,
    manifest: object,
    outputs: dict[str, bytes],
    replace: bool = False,
) -> str:
    """Publish one exact generated bundle, with replacement requiring consent."""

    relative_dir = _repo_relative(repo_root, output_dir, label="paper output")
    validated = validate_performance_paper_manifest(manifest, outputs=outputs)
    corpus_version = _source_corpus_version(validated["source"]["path"])
    if relative_dir != f"paper/generated/{corpus_version}":
        raise PerformancePaperError("invalid performance paper output directory")
    desired = dict(outputs)
    desired[MANIFEST] = serialize_performance_paper_manifest(validated)
    try:
        if output_dir.exists() and (output_dir.is_symlink() or not output_dir.is_dir()):
            raise PerformancePaperError("invalid performance paper output directory")
        output_dir.mkdir(parents=True, exist_ok=True)
        existing = {entry.name: entry for entry in output_dir.iterdir()}
    except OSError as exc:
        raise PerformancePaperError(
            "invalid performance paper output directory"
        ) from exc
    if set(existing) - set(_ALL_FILES):
        raise PerformancePaperError("unexpected performance paper output")
    if set(existing) == set(_ALL_FILES) and all(
        _read_existing(existing[name]) == desired[name] for name in _ALL_FILES
    ):
        return "unchanged"
    if existing and not replace:
        raise PerformancePaperError(
            "performance paper outputs already exist or are incomplete"
        )

    if replace:
        temporary: dict[str, Path] = {}
        try:
            for name in _ALL_FILES:
                temp = output_dir / f".{name}.new"
                if temp.exists() or temp.is_symlink():
                    raise PerformancePaperError(
                        "stale performance paper temporary file"
                    )
                with temp.open("xb") as target:
                    target.write(desired[name])
                    target.flush()
                    os.fsync(target.fileno())
                temporary[name] = temp
            for name in _ROW_FILES:
                os.replace(temporary[name], output_dir / name)
            os.replace(temporary[MANIFEST], output_dir / MANIFEST)
        except (OSError, PerformancePaperError) as exc:
            for temp in temporary.values():
                try:
                    temp.unlink(missing_ok=True)
                except OSError:
                    pass
            if isinstance(exc, PerformancePaperError):
                raise
            raise PerformancePaperError(
                "failed to replace performance paper outputs"
            ) from exc
    else:
        created = []
        try:
            for name in (*_ROW_FILES, MANIFEST):
                path = output_dir / name
                with path.open("xb") as target:
                    target.write(desired[name])
                    target.flush()
                    os.fsync(target.fileno())
                created.append(path)
        except OSError as exc:
            for path in created:
                try:
                    path.unlink(missing_ok=True)
                except OSError:
                    pass
            raise PerformancePaperError(
                "failed to create performance paper outputs"
            ) from exc

    retained = {name: _read_existing(output_dir / name) for name in _ALL_FILES}
    if retained != desired:
        raise PerformancePaperError("performance paper outputs changed after write")
    try:
        decoded = json.loads(retained[MANIFEST].decode("ascii"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise PerformancePaperError("performance paper manifest is unreadable") from exc
    validate_performance_paper_manifest(decoded, outputs=outputs)
    return "replaced" if replace else "created"
